### ISSUE TITLE
Simplify Marker Creation

### ISSUE THREAD

**Issue by Zoriot** [MiraculixxT/bluemap-marker#25]
It would be great if you simplify the Marker Creation more:
- Allow executing commands from console (So you dont have to tab between BlueMap and Minecraft)
- Make a Command where you can create a POI Marker with one Command (kinda simular how [BlueMarker ](https://www.spigotmc.org/resources/bluemarker.110946/)does with Signs)
- If some mistyped information, allow discarding last step

Also the Modrinth/Download Links should be added to the Readme & the ToDo ``Adding a way to edit markers and marker-sets after build/creating them`` should be removed, bc i think thats already implemented.

**Comment by Zoriot** [comment]
`14:44:05

4004 issued server command: /btemplate delete zotest true

WARN
14:44:05

Exception in thread "DefaultDispatcher-worker-1" java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
	at bmm-paper-2.1.7.jar//de.miraculixx.bmm.commands.TemplateCommand$templateCommand$lambda$11$lambda$10$lambda$9$lambda$8$$inlined$anyExecutorAsync$1$1.invokeSuspend(CommandExtensions.kt:24)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:832)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3b391ccc, Dispatchers.Default]`
Deleting Marker Templates Seems not to work. (Deleting the Marker Tamplate inside works)

**Comment by Zoriot** [comment]
Currently using the Tamplates doesnt really work for line`s. Would be great if you can use that too
